networks:
  PostgreSQL-net:
    driver: bridge
    name: PostgreSQL-net

services:
  postgres:
    container_name: PostgreSQL
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - PostgreSQL-net
    restart: unless-stopped

  pgadmin:
    container_name: PgAdmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - PostgreSQL-net
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
